imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
  dbal:
    default_connection: default
    connections:

      default:
        server_version: "5.6"
        driver:   pdo_mysql
        host:     localhost
        port:     ~
        dbname:   multidb
        user:     root
        password: root
        charset:  UTF8

      tenant:
        server_version: "5.6"
        driver:   pdo_mysql
        host:     %database_host%
        port:     %database_port%
        dbname:   ~
        user:     ~
        password: ~
        wrapper_class: AppBundle\Connection\Wrapper

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    default_entity_manager: default

    entity_managers:
      default:
        auto_mapping:     false # disabled so we can assign entities to our own connections
        connection:       default
        mappings:
            AppBundle:
              type:       yml
              mapping:    true
              dir:        %kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/App
              prefix:     AppBundle\Entity
              is_bundle:  false

      tenant:
        auto_mapping:     false # disabled so we can assign entities to our own connections
        connection:       tenant
        mappings:
          Invoices:
            type:       yml
            mapping:    true
            dir:        %kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/Client
            prefix:     Client
            is_bundle:  false
